### PR TITLE
table names are case sensitive in mysql

### PR DESCRIPTION
**Pull request by mgolden-noodle**
I am seeing errors in my catalina.out.  This should fix them.

### CODE REVIEW

**Comment by steveswinsburg** [comment]
This is to do with your MySQL config being case sensitive. You should have:
`lower_case_table_names=1` in your MySQL config. Can you check that it is there?

**Comment by mgolden-noodle** [comment]
It is there now, but it only works if it's there at the time the database
is created.  Once the database is built, the table names are fixed.

Aside from that though, I would note that nowhere in sakai is the table
referred to in lower case, and I think it's to avoid the problem that I
have noticed.  You can see it by doing "grep -rHn sakai_event
[SAKAI_SOURCE_DIR]". The one line (outside a comment) you'll find is line
89
of sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAggregateJobImpl.java,
but that's a special case:

 73    private String MYSQL_GET_EVENT                  = "select " +
MYSQL_DEFAULT_COLUMNS + MYSQL_CONTEXT_COLUMN + " " +
 74                                                         "from
SAKAI_EVENT e join SAKAI_SESSION s on e.SESSION_ID=s.SESSION_ID " +
 75                                                         "where EVENT_ID
>= ? and EVENT_ID < ? " +
 76                                                         "order by
EVENT_ID asc ";
...

 88     private String ORACLE_GET_EVENT = "SELECT " +
ORACLE_DEFAULT_COLUMNS + ORACLE_CONTEXT_COLUMN +
 89                 " FROM sakai_event e JOIN sakai_session s ON
e.session_id = s.SESSION_ID" +
 90                 " WHERE event_id >= ? AND event_id < ? ORDER BY
event_id ASC";

It seems that an attempt is being made (for mysql) to refer to the table
names in upper case, so I think it's worth doing in the engagement code as
well.

Mitch Golden
CTO
Noodle Partners, Inc.
59 Chelsea Piers, Suite 200, New York, NY, 10011
+1 646 289 7834 | mgolden@noodle.com | noodle-partners.com

**Comment by steveswinsburg** [comment]
I think you can set it and then just restart mysqld, but will merge for consistency anyway 👍

**Comment by mgolden-noodle** [comment]
From my understanding, mysql actually uses file names that match table names. Therefore the case sensitivity of the table names is determined by the case sensitivity of file names in the underlying os. So on windows the table names are always case insensitive on Unix case sensitive. I believe that setting that flag just just downcases the table names, but if the file was already created upper case it won't work.

All pretty silly if you ask me.

Sakai seems not to require setting the flag so it's best to treat table names as case sensitive. What is bad is that they didn't follow a convention to make them either all upper case or all lower case. There are some of each.


-- 
Mitch Golden
CTO, Noodle Partners

**Pull request merged**
